### PR TITLE
Adding tabs in workshop page

### PR DESCRIPTION
**Pull request by clefourrier**
Fixing https://github.com/acl-org/acl-2020-virtual-conference/issues/251

### CODE REVIEW

**Comment by clefourrier** [comment]
This will need https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/74

**Comment by raosudha89** [comment]
@clefourrier  It looks like the other PR (https://github.com/acl-org/acl-2020-virtual-conference/pull/254) went in while this was under works which creates a conflict.

**Comment by clefourrier** [comment]
@raosudha89 You chose to remove the calendar view in the workshop page?

**Comment by raosudha89** [comment]
@clefourrier I thought the plan was to not have the calendar view and simply have the tabs. My apologies if that was not the goal. I was just merely trying to resolve the conflict and I thought in your version you did not want to keep the calendar. 

Feel free to ignore my changes and push yours.

**Comment by clefourrier** [comment]
@raosudha89 Quite frankly, I don't really have an opinion ^^ If you (ACL organizers) want to have both the calendar and tabs, I'll look into a different merge. If it is indifferent, please merge and close the issue, it's completely fine by me.

**Comment by raosudha89** [comment]
> @raosudha89 Quite frankly, I don't really have an opinion ^^ If you (ACL organizers) want to have both the calendar and tabs, I'll look into a different merge. If it is indifferent, please merge and close the issue, it's completely fine by me.

Okay, in that case can you locally fix the format check that is failing currently in this PR? (by running make format locally)
Also make sure that the changes I did to resolve conflicts with master branch is working as expected i.e. it doesn't break anything?

Sorry, I am not able to check this PR locally and do these things.

**Comment by clefourrier** [comment]
@raosudha89 Np for the PR check, I fixed the merge in the first commit, then ran a make format in the second one.

However, I don't understand why the format check is still failing. Do you have an idea?

**Comment by raosudha89** [comment]
@clefourrier  Aah, I don't think now its a format related issue. This is the error message 'miniconf/load_site_data.py:153:8: W0612: Unused variable 'day' (unused-variable)'

I think this will be fixed if we  merge the sitedata in. So can you do the following in your local repo:

git add sitedata_acl2020
git commit -m 'bump_sitedata'
git push

This will case the sitedata to be updated and then the 'day' variable will not be unused.

Thanks

**Comment by hao-fang** [comment]
@clefourrier @raosudha89 I'm fixing it.

**Comment by hao-fang** [comment]
> @clefourrier Aah, I don't think now its a format related issue. This is the error message 'miniconf/load_site_data.py:153:8: W0612: Unused variable 'day' (unused-variable)'

For future reference -- this is a pylint error.

**Comment by raosudha89** [comment]
@hao-fang  Can I merge this for now? I will replace 'monday/fri/sat' with 'july 5/9/10' in a different PR. Thanks.

**Pull request merged**
