### PR TITLE
72 demo papers

### PR DESCRIPTION
**Pull request by georgepar**
Create demo papers subpage under papers and add demo poster page

### CODE REVIEW

**Comment by georgepar** [comment]
Hi Hao,

Here's how it looks. If you have any ideas let me know.

Needs an update from [this PR](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/32)

Screenshot from 2020-06-20 21-11-51
Screenshot from 2020-06-20 21-12-18

**Comment by hao-fang** [comment]
@georgepar This in general looks good!
I had some comments in https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/32#pullrequestreview-434449649. 
I think on the paper page, the "Demo Session 4C" should be "Session 4C", and we should show a "Track: Demo" somewhere in the page.
Please take a look at the `sitedata_acl2020/poster_schedule.yml` file to get some sense about the schedule.
(I agree this is now confusing, and I need to think about it a little harder.)

At a high level, main conference papers, demo papers, and student research workshop papers all share the same "session" slots, but they belong to different tracks.

**Comment by raosudha89** [comment]
Hi @georgepar and @hao-fang , I am trying to understand the layout of the 'Papers' tab in general.

Is the plan to have a separate tab for Main Conference Papers, Demo Papers and SRW papers?

**Comment by hao-fang** [comment]
@raosudha89 That sounds fine to me. We can improve it when we have time.

**Comment by hao-fang** [comment]
Closing this with #171 and #167.

**Pull request closed without merging**
