### PR TITLE
minor fix: papers detail styling

### PR DESCRIPTION
**Pull request by SebastinSanty**
Fixing the height of the papers detail panel (340px -> 220px) (tested on several media sizes). Also, contrast background for easy reading.

### CODE REVIEW

**Comment by hao-fang** [comment]
@SebastinSanty can you fix the Lint error? You can run `make format` locally.

**Comment by hao-fang** [comment]
@SebastinSanty sorry I don't know why the Github Action failed at the checkout code step.
image

My guess is that you are making the PR from your own fork...
Can you try to make a branch on our repo, and then re-create this PR?
Thanks!

**Comment by SebastinSanty** [comment]
@hao-fang Yes, I saw this error and was working on that. Thanks for the tip! Will try fixing this asap.

**Comment by SebastinSanty** [comment]
@hao-fang I don't have access to make a branch on this repo

**Comment by hao-fang** [comment]
> @hao-fang I don't have access to make a branch on this repo.

@SebastinSanty You have a pending invitation which you need to accept.
image

**Comment by SebastinSanty** [comment]
@hao-fang Thanks! It was in my spam. I will close this and make a new PR.

**Pull request closed without merging**
