### PR TITLE
Add paper share

### PR DESCRIPTION
**Pull request by tlikhit**
Implements paper-sharing as mentioned in #465. Currently copies following template to clipboard, please check and edit:
> Here's an interesting read from #ACL2020 -
> paperTitle: paper_non_pdf_link

### CODE REVIEW

**Comment by hao-fang** [comment]
@tlikhit Thanks! It seems that this only "copy" a text to the clipboard. My first impression is that it will pop up/open a window..
Can we directly implement something like "Share to Twitter, Email, etc."?

**Comment by tlikhit** [comment]
@hao-fang Ah, I agree. I just implemented the request from the tweet mentioned in the issue. I'll implement that in a new branch :) What platforms should be supported?

**Comment by hao-fang** [comment]
@tlikhit Hmmm probably FB, Twitter, LinkedIn, Email?
(I just saw it from SlidesLive pages)
image

I guess Email is probably the default one. And we don't have to do FB/Twitter/LinkedIn if that's too much.

**Comment by tlikhit** [comment]
@hao-fang Cool, will do 👍 
I'm closing this and will implement this on a new branch.

**Pull request closed without merging**
