### PR TITLE
Calendar replacement

### PR DESCRIPTION
**Pull request by jcklie**
I changed the calendar to https://fullcalendar.io/ and loaded the existing events. Please try it out. We have so many events that the calendar is really fully, we might want a filter. Please try the timezone thingy.

image
image
image

### CODE REVIEW

**Comment by hao-fang** [comment]
@jcklie This looks nice!
It seems that the `make freeze` failed. Can you try to figure out why?
Also I think @raosudha89 has updated `main_calendar.json` to add the plenary sessions information. Maybe you want to 
`cd sitedata_acl2020 && git pull`

**Comment by raosudha89** [comment]
@jcklie  Sorry, I didn't know you were working on this. I created main_calendar.json slighly differently. Since there are too many tutorials and workshops to all be listed on main schedule, I just added them as overall sessions. Below is the screenshot. 

image

**Comment by raosudha89** [comment]
@jcklie  and @hao-fang  I think it might better for me to revert the changes I made, let @jcklie  submit his changes to main_calendar.json and I can add the missing plenary sessions info.

**Comment by hao-fang** [comment]
@jcklie ok -- I fixed the `make freeze` error.
see this commit https://github.com/acl-org/acl-2020-virtual-conference/pull/190/commits/c7fb0d7897b6697f4a4f8816d9bce2af9b4d9b22 for the changes

**Pull request merged**
