### PR TITLE
re-formatting sponsors list

### PR DESCRIPTION
**Pull request by Chandrahasd**
Aligned the sponsors' list to center.
Removed the horizontal rule.

### CODE REVIEW

**Comment by hao-fang** [comment]
@Chandrahasd Thanks! Can you attach a screenshot here so we can see how it looks after the change?

**Comment by Chandrahasd** [comment]
> @Chandrahasd Thanks! Can you attach a screenshot here so we can see how it looks after the change?

Sure.
Please find it here.
Let me know if something needs to be changed.
Screen Shot 2020-06-15 at 12 51 47 PM

**Comment by hao-fang** [comment]
@Chandrahasd Thanks.
Can you try to follow the same style as https://naacl2019.org/sponsors/list/ and https://www.emnlp-ijcnlp2019.org/sponsors/general/?
I guess you can find some code in this repo https://github.com/naacl-org/naacl-hlt-2019.

Also, can you make the "Click on logos to visit Virtual Exhibit Spaces" more salient? (maybe a different font / color)? Not sure if it is possible. It's fine if there is no good solution.

**Comment by Chandrahasd** [comment]
Added hover-box on logos, put a slight emphasis on "Click on logos to visit Virtual Exhibit Spaces". @jcklie please let me know if this seems fine or I should try other ways (e.g., colors).

I am also planning to add a sidebar similar to the one on the right-side [here](https://acl2020.org/sponsors/list/). @hao-fang please let me know if we do not want it.

Screen Shot 2020-06-17 at 6 41 52 PM

**Comment by jcklie** [comment]
@Chandrahasd It looks nice, we just need to wait what happens when we use the real sponsor images. I also would add the thank you text from the [ACL Sponsor Page](https://acl2020.org/sponsors/list/):

> ACL 2020 is grateful to all its sponsors, who are listed below. We simply couldn’t run the conference without the help of these generous companies. We thank them sincerely for their ongoing support of the NLP/CL community.

**Comment by jcklie** [comment]
@Chandrahasd It looks so much better now! I merged master so now you also have the real logos. One last thing: Can you make it so that the border of the logos is square for all and has the same size?

Bad:

image

Good:

https://naacl2019.org/sponsors/list/

I do not know whether the border we have looks good or not, you can decide. I would prefer the logos centered in the box though.

**Comment by jcklie** [comment]
And maybe smaller and more border left and right?

**Comment by jcklie** [comment]
@hao-fang WDYT? I cannot merge by myself.

**Comment by jcklie** [comment]
image

**Pull request merged**
