### PR TITLE
Improved Home Page layout

### PR DESCRIPTION
**Pull request by tlikhit**
I've played around with the layout quite a bit and these are the changes I ended up with:
- adopt 2 column layout similar to https://iclr.cc/virtual_2020/
- increased video sizes
- made video titles more concise
- fix stray divs and make slideslive embeds properly responsive
Relevant issues: #19, #169 

I still need to make some minor spacing tweaks etc. but will proceed if the basic design is okay.
Some questions:
- Will the video messages be using slides? By default, slideslive embed only shows the video view.
If they use slides, I'll either have to tweak the embed to open in full-screen upon click to see the video and slides side-by-side or make the videos and slides full-width. On a related note, can anyone link to slideslive documentation? I couldn't find details on the embed params anywhere...
- I found the font size a bit too big. Is this intentional or can I make it smaller, say to the scale of the ICLR page?
 
screenshot-localhost-5000-index-html-1592982237654

### CODE REVIEW

**Comment by raosudha89** [comment]
@tlikhit  Thanks for working on this. I think these changes look good. Below are my answers to some of your questions:

> Will the video messages be using slides? 
No, both the video messages will have only video (no slides).

**Comment by tlikhit** [comment]
@raosudha89 got it! Also, would it be okay if you first merge this in? I'll address font-sizes and minor design improvements in another PR as I'll need to also ensure cross-page consistency.

**Comment by jcklie** [comment]
@tlikhit I did the font size that way to match the style on the ACL home page

**Comment by tlikhit** [comment]
@jcklie Ah, I see. Was just wondering because it seemed bigger than other pages. Now that I look at it again, doesn't look too bad after increased padding. Might retain the size and just improve consistency.

**Comment by jcklie** [comment]
The one on the ACL page scales when you resize your browser, I think ours does not. If you change it, please also change it on the sponsor and sponsors page.

**Pull request merged**
