### PR TITLE
Add demo link (#32)

### PR DESCRIPTION
**Pull request by GuyAglionby**
If available, show a link to the demo alongside the paper + abstract link

image

### CODE REVIEW

**Comment by hao-fang** [comment]
This looks good to me.
Let me know if you want me to approve this PR. (I didn't receive notification b/c I wasn't added as a reviewer.) Not sure if you are still working on this or not.

**Comment by GuyAglionby** [comment]
Ah sorry, yes this is good to merge thanks

**Comment by hao-fang** [comment]
@GuyAglionby The CI fails. Can you run `make freeze` and fix the error? Thanks!

**Comment by GuyAglionby** [comment]
Sorry for the multiple commits - it wasn't clear to me what was causing the initial test failure. The code formatting error is now fixed. The check now fails because `demos.csv` doesn't exist - once https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/5 is merged and this repo bumped to reflect that, the test should pass.

**Comment by hao-fang** [comment]
@GuyAglionby I merged that PR. Can you try again? You may need to merge master and resolve some conflicts on `main.py`

**Pull request merged**
