### PR TITLE
Add functionality to filter selected papers

### PR DESCRIPTION
**Pull request by SebastinSanty**
I felt this would be good to have to easily sort through chosen papers

### CODE REVIEW

**Comment by SebastinSanty** [comment]
non-selected
selected

**Comment by hao-fang** [comment]
@SebastinSanty hmm... i don't know exactly how they remember the selection. There is a notice
image
But we do not have a server to store this cookie. So the selection will **not** be remembered.

Do you have any suggestion about this? Probably we should modify the notice and see your selection will only be stored locally?

**Comment by SebastinSanty** [comment]
@hao-fang Yes, that's right, these selections are stored locally. Maybe changing the terminology to 'Seen' or 'Visited' might help? Accordingly, we can change the cookie notice.

**Comment by hao-fang** [comment]
@SebastinSanty sounds good! Can you make the changes in this PR?

**Comment by SebastinSanty** [comment]
@hao-fang I have renamed the term to 'visited'.

**Comment by hao-fang** [comment]
@SebastinSanty can you check the cookie notice and make some change as well? Thanks!

**Comment by SebastinSanty** [comment]
@hao-fang I felt that the cookie notice is apt - the 'visited' filter button enables one to navigate the already visited papers which are stored as cookies as the notice says. Are you suggesting me to add a note about the 'visited' filter button?

**Comment by hao-fang** [comment]
@SebastinSanty I see. Then let's keep it as it is.

**Pull request merged**
