### PR TITLE
Make different tabs for different days and split speakers by days

### PR DESCRIPTION
**Pull request by georgepar**
Follow ICLR and split speakers in days 
Needs https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/19 to get merged
Related issue: #23

### CODE REVIEW

**Comment by georgepar** [comment]
@hao-fang Let me know if this looks like what you expected and then we can add more speakers / sessions

Do you want to add all the items from the print screens in this comment?
https://github.com/acl-org/acl-2020-virtual-conference/issues/23#issuecomment-645713690

**Comment by georgepar** [comment]
Also build fails because it needs a bump in sitedata -> acl-org/acl-2020-virtual-conference-sitedata#19

**Comment by hao-fang** [comment]
@georgepar I merged the sitedata PR. Can you bump the version here?

**Comment by georgepar** [comment]
> @georgepar I merged the sitedata PR. Can you bump the version here?

done.

**Pull request merged**
