### PR TITLE
Update tutorial page with all basic information

### PR DESCRIPTION
**Pull request by raosudha89**

### CODE REVIEW

**Comment by raosudha89** [comment]
@hao-fang: I am not sure why I am failing the format check. Can you help me figure this out?

**Comment by hao-fang** [comment]
> @hao-fang: I am not sure why I am failing the format check. Can you help me figure this out?

@raosudha89 Did you run `make format` locally? Make sure you have followed instructions [here](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/CONTRIBUTING.md) to set up your local environment first.

**Comment by raosudha89** [comment]
> > @hao-fang: I am not sure why I am failing the format check. Can you help me figure this out?
> 
> @raosudha89 Did you run `make format` locally? Make sure you have followed instructions [here](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/CONTRIBUTING.md) to set up your local environment first.

Aah good catch, I did not setup the local environment correctly. I will fix that. Thanks.

**Comment by raosudha89** [comment]
@hao-fang  I followed the steps under: https://github.com/acl-org/acl-2020-virtual-conference/blob/master/CONTRIBUTING.md

But when at the end of the steps under 'Build', when I run make, I get this error:

(isort -rc main.py scripts/ chat/ --check-only --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=88) && (black -t py37 --check main.py scripts/ chat/) || (echo "run \"make format\" to format the code"; exit 1)
ERROR: /mnt/c/Users/sudhra/OneDrive - Microsoft/ACL2020_Website/acl-2020-virtual-conference/scripts/parse_calendar.py Imports are incorrectly sorted.
ERROR: /mnt/c/Users/sudhra/OneDrive - Microsoft/ACL2020_Website/acl-2020-virtual-conference/scripts/qa_schedule_import.py Imports are incorrectly sorted.
ERROR: /mnt/c/Users/sudhra/OneDrive - Microsoft/ACL2020_Website/acl-2020-virtual-conference/scripts/reduce.py Imports are incorrectly sorted.
ERROR: /mnt/c/Users/sudhra/OneDrive - Microsoft/ACL2020_Website/acl-2020-virtual-conference/chat/make_poster_rooms.py Imports are incorrectly sorted.
run "make format" to format the code
Makefile:32: recipe for target 'format-check' failed
make: *** [format-check] Error 1

**Comment by hao-fang** [comment]
@raosudha89 did you run ‘make format’ to fix the errors?

**Comment by raosudha89** [comment]
When I run make format, I get this error. How do I upgrade npm?

make format
isort -rc main.py scripts/ chat/ --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=88
Fixing /mnt/c/Users/sudhra/OneDrive - Microsoft/ACL2020_Website/acl-2020-virtual-conference/scripts/parse_calendar.py
Fixing /mnt/c/Users/sudhra/OneDrive - Microsoft/ACL2020_Website/acl-2020-virtual-conference/scripts/qa_schedule_import.py
Fixing /mnt/c/Users/sudhra/OneDrive - Microsoft/ACL2020_Website/acl-2020-virtual-conference/scripts/reduce.py
Fixing /mnt/c/Users/sudhra/OneDrive - Microsoft/ACL2020_Website/acl-2020-virtual-conference/chat/make_poster_rooms.py
black -t py37 main.py scripts/ chat/
All done! ✨ 🍰 ✨
10 files left unchanged.
npx prettier static/js/app.js static/js/calendar.js static/js/gdpr_cookies.js static/js/ical.js static/js/icons.js static/js/lazy_load.js static/js/little_helpers.js static/js/papers.js static/js/paper_vis.js static/js/pdf_render.js static/js/persistor.js static/js/schedule.js static/js/time-extend.js static/js/typeahead.bundle.js static/css/Cuprum.css static/css/Exo.css static/css/Lato.css static/css/lazy_load.css static/css/main.css static/css/paper_vis.css static/css/typeahead.css --write
prettier requires at least version 10.13.0 of Node, please upgrade
Makefile:17: recipe for target 'format-web' failed
make: *** [format-web] Error 1

**Comment by raosudha89** [comment]
My npm version is 3.5.2 and I see that we need atleast 6.7.0. I will try upgrading it.

**Comment by raosudha89** [comment]
@hao-fang 

I upgraded my npm 6.14.5  But when I run the 'make' command, I still get an error:

prettier requires at least version 10.13.0 of Node, please upgrade
Makefile:32: recipe for target 'format-check' failed
make: *** [format-check] Error 1

When I check the version of node, I find that my version is 8.10.0 
I thought that upgrading npm will automatically give me an upgraded version of node. But it doesn't seem to be the case.

Any thoughts?

**Comment by raosudha89** [comment]
I was finally able to resolve this issue by explicitly upgrading node as suggested here: https://phoenixnap.com/kb/update-node-js-version 

The 'make' command runs successfully now.

**Comment by kaushal0494** [comment]
@hao-fang  I also received a similar error as @raosudha89.   
make format
isort -rc main.py scripts/ chat/ --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=88
black -t py37 main.py scripts/ chat/
All done! ✨ 🍰 ✨
10 files left unchanged.
npx prettier static/js/lazy_load.js static/js/gdpr_cookies.js static/js/pdf_render.js static/js/time-extend.js static/js/persistor.js static/js/little_helpers.js static/js/schedule.js static/js/calendar.js static/js/app.js static/js/papers.js static/js/icons.js static/js/typeahead.bundle.js static/js/ical.js static/js/paper_vis.js static/css/main.css static/css/typeahead.css static/css/Lato.css static/css/paper_vis.css static/css/Cuprum.css static/css/Exo.css static/css/lazy_load.css --write
prettier requires at least version 10.13.0 of Node, please upgrade
Makefile:17: recipe for target 'format-web' failed
make: *** [format-web] Error 1

am I missing something?

**Comment by raosudha89** [comment]
> @hao-fang I also received a similar error as @raosudha89.
> make format
> isort -rc main.py scripts/ chat/ --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=88
> black -t py37 main.py scripts/ chat/
> All done! ✨ 🍰 ✨
> 10 files left unchanged.
> npx prettier static/js/lazy_load.js static/js/gdpr_cookies.js static/js/pdf_render.js static/js/time-extend.js static/js/persistor.js static/js/little_helpers.js static/js/schedule.js static/js/calendar.js static/js/app.js static/js/papers.js static/js/icons.js static/js/typeahead.bundle.js static/js/ical.js static/js/paper_vis.js static/css/main.css static/css/typeahead.css static/css/Lato.css static/css/paper_vis.css static/css/Cuprum.css static/css/Exo.css static/css/lazy_load.css --write
> prettier requires at least version 10.13.0 of Node, please upgrade
> Makefile:17: recipe for target 'format-web' failed
> make: *** [format-web] Error 1
> 
> am I missing something?

Follow the steps here https://phoenixnap.com/kb/update-node-js-version to upgrade the version of your node.

**Comment by raosudha89** [comment]
@hao-fang, this seems to have passed all checks now. But I noticed that it added ~2000 new lines to package-lock.json file. I don't understand things well to know if this is an issue or not. I will defer it to you.

**Comment by hao-fang** [comment]
> @hao-fang, this seems to have passed all checks now. But I noticed that it added ~2000 new lines to package-lock.json file. I don't understand things well to know if this is an issue or not. I will defer it to you.

@raosudha89 Can you do this
```
rm -rf node_modules/
git checkout master package-lock.json package.json
npm install
```
And see if the the `package-lock.json` still changes by looking at `git status`?

**Comment by raosudha89** [comment]
> rm -rf node_modules/

When I run this cmd, I get this error. I am not sure if I should use sudo?

rm: cannot remove 'node_modules/npm/node_modules/retry': Directory not empty

**Comment by raosudha89** [comment]
@hao-fang 

I forced removed that folder and did as you suggested and my make ran successfully with no additional changes to package json files. Thanks so much!

**Comment by hao-fang** [comment]
@raosudha89 Cool! Let's do this. Can you make changes on #106 first to add the TODO notes about acknowledgements. We will merge that. And then we can merge this one, because it seems that this PR involves changes from #106.

**Comment by raosudha89** [comment]
> @raosudha89 Cool! Let's do this. Can you make changes on #106 first to add the TODO notes about acknowledgements. We will merge that. And then we can merge this one, because it seems that this PR involves changes from #106.

Done. Feel free to review both and then merge.

**Pull request merged**
