### PR TITLE
add new sponsor bytedance pdfs

### PR DESCRIPTION
**Pull request by e-tony**

### CODE REVIEW

**Comment by hao-fang** [comment]
@e-tony Can you directly create branch on this repo instead of making a fork?
It will be easier to make changes. And using a fork would not be able to pass the CI check here.

**Comment by e-tony** [comment]
Yes, will do! Thanks for the notice. 

It seems I also updated the "eslint-config-airbnb" from "^18.1.0" to "^18.2.0" in "package.json". Could this introduce problems?

**Comment by hao-fang** [comment]
> Yes, will do! Thanks for the notice.
> 
> It seems I also updated the "eslint-config-airbnb" from "^18.1.0" to "^18.2.0" in "package.json". Could this introduce problems?

@e-tony Can you remove your `node_modules` locally, reset `package.json`, and run `npm install`? It should not change the `package.json` file.

**Comment by Chandrahasd** [comment]
> Yes, will do! Thanks for the notice.
> 
> It seems I also updated the "eslint-config-airbnb" from "^18.1.0" to "^18.2.0" in "package.json". Could this introduce problems?

To be on the safer side, I think you can skip changing 'package.json'.

**Comment by hao-fang** [comment]
Close this with #382

**Pull request closed without merging**
