### PR TITLE
Update calendar.js

### PR DESCRIPTION
**Pull request by srush**
Add a nowIndicator (line that shows the time).

### CODE REVIEW

**Comment by srush** [comment]
image

**Comment by hao-fang** [comment]
@srush thanks a lot! I'll make a PR -- we use a private submodule to protect all the Zoom links in `sitedata_acl2020` so you couldn't pass the Github Action check with your own fork. I have added you to both repos now.

**Comment by hao-fang** [comment]
@srush Oh we have used a different calendar here https://fullcalendar.io/ so this PR may not work in this repo

**Comment by hao-fang** [comment]
Close with #531

**Comment by srush** [comment]
Oh I see. Looks like you figured it out. :+1:

**Pull request closed without merging**
