### PR TITLE
Make changes on site_data.py and load_site_data.py

### PR DESCRIPTION
**Pull request by penny9287**
Make changes on site_data.py and load_site_data.py to add the information of presentation_id

### CODE REVIEW

**Comment by hao-fang** [comment]
@penny9287 Can you run `make format` locally? It seems that the indent is not right.

**Comment by penny9287** [comment]
I will check it.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/acl-org/acl-2020-virtual-conference/pull/170#issuecomment-647915838",
"url": "https://github.com/acl-org/acl-2020-virtual-conference/pull/170#issuecomment-647915838",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by penny9287** [comment]
@hao-fang I'm afriad I can't solve this issue. I always make mistakes in the "Format check" section.

**Comment by hao-fang** [comment]
@penny9287 no problem. I can take care of this.
You might need to follow https://github.com/acl-org/acl-2020-virtual-conference/blob/master/CONTRIBUTING-ACL2020.md to set up your local environment first next time.

**Pull request closed without merging**
