### PR TITLE
Workshop schedule calendar

### PR DESCRIPTION
**Pull request by raosudha89**
Note: This PR has dependency on https://github.com/acl-org/acl-2020-virtual-conference/pull/151 and https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/38

This PR needs more work. @kaushal0494 It would be great if you could help me fix the following issue that I am unable to resolve:
- We need the main workshops page to display three dayview calendars on the three tabs (Sunday, Thursday, Friday). 
- I have the code for it in the PR. But I have commented out two out of three tabs since when I try to display all three, it gives some issues. 
- Would it be possible for you to checkout this PR and work on fixing this issue? 
- OR we can merge this for now and I can create a new issue for working the fix. 

@hao-fang  Let us know what you think.

### CODE REVIEW

**Comment by hao-fang** [comment]
@kaushal0494 can you take over this PR and post the screenshot of the outcome?

**Comment by kaushal0494** [comment]
@hao-fang  @raosudha89  Sure! let me check and try to fix this. I will work on this PR now.

**Comment by kaushal0494** [comment]
@raosudha89 I am not sure what exactly the issue is- I am consistently checking but unable to debug.  I will give one more try!

**Comment by tlikhit** [comment]
@kaushal0494 hey there! were you able to fix this or is it okay if I start working on this?

**Comment by kaushal0494** [comment]
@tlikhit Yes, please have look at this.  Thank you!

**Comment by raosudha89** [comment]
Thanks @tlikhit Please check the latest changes made to the overall schedule page https://virtual.acl2020.org/schedule.html#tab-calendar  You can borrow the changes there to make this work.

**Comment by tlikhit** [comment]
Okay, I found that the problem was in make_cal, spent too much time trying to debug bootstrap 😅
I will send in a PR soon!

**Comment by tlikhit** [comment]
I'm having trouble fixing this...Other than some bootstrap fixes, the problem seems to be in the first part of make_cal().
getUrlParameter("tz") returns the string "undefined" and so the calendar isn't displayed and page keeps refreshing.
I've tried fixing it, but after I modify static js files, the changes aren't reflected in served files when I do make run.
Any help appreciated!

**Comment by raosudha89** [comment]
@jcklie  Can you look into this? At a high-level we want the main workshops page to display the workshop schedule for the workshops on July 5, July 9, July 10 on three tabs.  But if displaying in different tabs is turning out to be difficult, we can also just use the week/day view as in the 'schedule' tab but we need to ensure that only three days are in the week view.

**Comment by raosudha89** [comment]
Closing this since @jcklie will replace this with a different calendar as discussed in this newly opened issue (https://github.com/acl-org/acl-2020-virtual-conference/issues/215).

Thanks @tlikhit and @kaushal0494  for all your help on this.

**Pull request closed without merging**
