### PR TITLE
QA session links in main calendar

### PR DESCRIPTION
**Pull request by clefourrier**
Pull request provided to solve https://github.com/acl-org/acl-2020-virtual-conference/issues/214

With this code, you can now click in the calendar and have the list of papers displayed for the selected QA session.

### CODE REVIEW

**Comment by raosudha89** [comment]
@clefourrier  Thanks for working on this. Can you provide us a screenshot here showing the output on clicking on one of the QA sessions?

**Comment by clefourrier** [comment]
image

**Comment by clefourrier** [comment]
To make it more obvious, if you look at the scrollbar:
image
 vs 
image

**Comment by raosudha89** [comment]
LGTM. But I will let @hao-fang also take a look and he can merge it then. 

Thanks @clefourrier

**Pull request merged**
