### PR TITLE
Revert "Calendar beautify"

### PR DESCRIPTION
**Pull request by raosudha89**
Reverts acl-org/acl-2020-virtual-conference#199

The schedule page is not working after this merge. @jcklie  Did the changes you made successfully run locally (via make run)?

### CODE REVIEW

**Comment by jcklie** [comment]
You need https://github.com/acl-org/acl-2020-virtual-conference-sitedata

**Comment by raosudha89** [comment]
> You need [acl-org/acl-2020-virtual-conference-sitedata#56](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/56) , I always forget the two repo situation 😢

Thanks. I just merged that PR. Let me run it locally again. Once it works, I will delete this PR. Thanks for the quick response :)

**Comment by raosudha89** [comment]
That PR works now. Closing this.

**Comment by jcklie** [comment]
Sorry for the trouble!

**Pull request closed without merging**
